[flake8]
# Eye candy
format = ${cyan}%(path)s${reset}:${yellow_bold}%(row)d${reset}:${green_bold}%(col)d${reset}: ${red_bold}%(code)s${reset} %(text)s

# I find 80-column to be way too narrow, and feel that 120 is a good number
max-line-length = 120

# Exclude some commonly stuff that we shouldn't bother about
exclude =
    .git,
    .virtualenv,
    __pycache__,
    */migrations/*,
    *~

# Cutting ourselves some slack
ignore =
  # D100: Missing docstring in public module
  D100,
  # D101: Missing docstring in public class
  D101,
  # D102: Missing docstring in public method
  D102,
  # D103: Missing docstring in public function
  D103,
  # D104: Missing docstring in public package
  D104,
  # D105: Missing docstring in magic method
  D105,
  # D106: Missing docstring in public nested class
  D106,
  # S001: Found module formatter
  S001,
  # P101: Format string does contain unindexed parameters
  P101

# I like double quotes, I really do
inline-quotes = double
multiline-quotes = double
